/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "operaciones.h"


void
operaciones_prog_1(char *host, int a, int b)
{
	CLIENT *clnt;
	struct Operandos  *result_1;
	struct Operandos  suma_1_arg;
	struct Operandos  *result_2;
	struct Operandos  producto_1_arg;
	struct Operandos  *result_3;
	struct Operandos  cociente_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, OPERACIONES_PROG, OPERACIONES_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	suma_1_arg.i = a;
	suma_1_arg.j = b;

	producto_1_arg = suma_1_arg;
	cociente_1_arg = suma_1_arg;

	result_1 = suma_1(&suma_1_arg, clnt);
	if (result_1 == (struct Operandos *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = producto_1(&producto_1_arg, clnt);
	if (result_2 == (struct Operandos *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_3 = cociente_1(&cociente_1_arg, clnt);
	if (result_3 == (struct Operandos *) NULL) {
		clnt_perror (clnt, "call failed");
	}

	printf("%d + %d = %f\n", suma_1_arg.i, suma_1_arg.j, result_1->res);
	printf("%d * %d = %f\n", suma_1_arg.i, suma_1_arg.j, result_2->res);
	printf("%d / %d = %f\n", suma_1_arg.i, suma_1_arg.j, result_3->res);

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host num1 num2\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	operaciones_prog_1 (host, atoi(argv[2]), atoi(argv[3]));
exit (0);
}
