/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "operaciones.h"

bool_t
xdr_Operandos (XDR *xdrs, Operandos *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->i))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->j))
		 return FALSE;
	return TRUE;
}
