/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _OPERACIONES_H_RPCGEN
#define _OPERACIONES_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct Operandos {
	int i;
	int j;
};
typedef struct Operandos Operandos;

#define OPERACIONES_PROG 0x31111111
#define OPERACIONES_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define SUMA 1
extern  double * suma_1(struct Operandos *, CLIENT *);
extern  double * suma_1_svc(struct Operandos *, struct svc_req *);
#define PRODUCTO 2
extern  double * producto_1(struct Operandos *, CLIENT *);
extern  double * producto_1_svc(struct Operandos *, struct svc_req *);
#define COCIENTE 3
extern  double * cociente_1(struct Operandos *, CLIENT *);
extern  double * cociente_1_svc(struct Operandos *, struct svc_req *);
extern int operaciones_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define SUMA 1
extern  double * suma_1();
extern  double * suma_1_svc();
#define PRODUCTO 2
extern  double * producto_1();
extern  double * producto_1_svc();
#define COCIENTE 3
extern  double * cociente_1();
extern  double * cociente_1_svc();
extern int operaciones_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_Operandos (XDR *, Operandos*);

#else /* K&R C */
extern bool_t xdr_Operandos ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_OPERACIONES_H_RPCGEN */
