/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "operaciones.h"

double *
suma_1_svc(struct Operandos *argp, struct svc_req *rqstp)
{
	static double  result;

	/*
	 * insert server code here
	 */
	result = argp->i + argp->j;
	return &result;
}

double *
producto_1_svc(struct Operandos *argp, struct svc_req *rqstp)
{
	static double  result;

	/*
	 * insert server code here
	 */
	result = argp->i * argp->j;
	return &result;
}

double *
cociente_1_svc(struct Operandos *argp, struct svc_req *rqstp)
{
	static double  result;

	/*
	 * insert server code here
	 */
	result = argp->i / (double) argp->j;
	return &result;
}
